### ISSUE TITLE
Runtime failing with `*_wrapper` not found

### ISSUE THREAD

**Issue by 3starblaze** [tristanstraub/thecreeps-godotclj#2]
## Preliminary information

OS: Ubuntu 20.04.3 LTS x86_64
Clojure: 1.10.3
Java (`java -version`):
```
openjdk version "17" 2021-09-14
OpenJDK Runtime Environment (build 17+35-Ubuntu-120.04)
OpenJDK 64-Bit Server VM (build 17+35-Ubuntu-120.04, mixed mode, sharing)
```
For brevity, paths are replaced with these:
- `<HOME_DIR>` - The home directory
- `<PROJECT_ROOT>` - The path to the cloned version of `thecreeps-godotclj`

## The report

The game built fine using:

    git submodule init
    git submodule update
    make

Though, when I tried to run the editor for the first time using
`./godotclj/scripts/godot.sh --editor --quit` this reflection warning is thrown:

```Reflection warning, meander/util/epsilon.cljc:758:24 - reference to field val can't be resolved.```

Also this same warning also appeared in the build:
```
[...]
clj -Scp [...]
Reflection warning, meander/util/epsilon.cljc:758:24 - reference to field val can't be resolved.
mkdir -p <PROJECT_ROOT>/build
gcc -I<PROJECT_ROOT>/godot-headers -I<PROJECT_ROOT>/build -I<PROJECT_ROOT>/godotclj/src/c -I<PROJECT_ROOT>/build -ggdb -c src/c/wrapper.c -o <PROJECT_ROOT>/build/wrapper.o --std=c11 -fPIC -rdynamic
[...]
```

It throws this message and also breaks the editor by corrupting the config (shows there are no projects and I have to go and reload my project folder again; resets zoom from 100% to 75%(auto)).

The first time it opens up the editor, loads assets, hits icon.png and freezes at `Reflection warning, meander/util/epsilon.cljc:758:24 - reference to field val can't be resolved.`. After some time (around 15secs) it throws the remaining stack trace.

The engine boots up like this:

1.  It takes 4 seconds for GUI to show up (which stays on the boot screen)
2.  After that, it takes 5 seconds for reflection warning to appear
3.  Finally, it takes 14 more seconds for editor to open with purple `Dodge the Creeps` main screen scene and to print the whole stack trace. Editor closes immediately afterwards

I tried doing this three times with the same `<HOME_DIR>/.config/godot/*`.

In next runs it returns this (probably because it managed to break internal config).

```
Godot Engine v3.4.stable.official.206ba70f4 - https://godotengine.org
OpenGL ES 3.0 Renderer: Mesa Intel(R) HD Graphics 520 (SKL GT2)
OpenGL ES Batching: ON
/lib/x86_64-linux-gnu/libasound.so.2: undefined symbol: snd_dlpath

ERROR: <USER_HOME>/.config/godot/editor_settings-3.tres:4 - Parse Error: Expected 4 arguments for constructor
   at: poll (scene/resources/resource_format_text.cpp:562)
ERROR: Failed to load resource '<USER_HOME>/.config/godot/editor_settings-3.tres'.
   at: load (core/io/resource_loader.cpp:206)
ERROR: Failed loading resource: <USER_HOME>/.config/godot/editor_settings-3.tres. Make sure resources have been imported by opening the project in the editor at least once.
   at: _load (core/io/resource_loader.cpp:270)
WARNING: Could not open config file.
     at: create (editor/editor_settings.cpp:961)
Reflection warning, meander/util/epsilon.cljc:758:24 - reference to field val can't be resolved.
[... stack trace same as before but with different functions]
```
Full stack trace.

```
Godot Engine v3.4.stable.official.206ba70f4 - https://godotengine.org
OpenGL ES 3.0 Renderer: Mesa Intel(R) HD Graphics 520 (SKL GT2)
OpenGL ES Batching: ON
/lib/x86_64-linux-gnu/libasound.so.2: undefined symbol: snd_dlpath

Reflection warning, meander/util/epsilon.cljc:758:24 - reference to field val can't be resolved.
:t #error {
 :cause Error looking up function 'godot_string_json_escape_wrapper': <PROJECT_ROOT>/build/libgodotclj_gdnative.so: undefined symbol: godot_string_json_escape_wrapper
 :via
 [{:type clojure.lang.Compiler$CompilerException
   :message Syntax error macroexpanding at (main_jvm.clj:27:3).
   :data {:clojure.error/phase :execution, :clojure.error/line 27, :clojure.error/column 3, :clojure.error/source main_jvm.clj}
   :at [clojure.lang.Compiler$InvokeExpr eval Compiler.java 3711]}
  {:type java.lang.reflect.InvocationTargetException
   :message nil
   :at [jdk.internal.reflect.NativeConstructorAccessorImpl newInstance0 NativeConstructorAccessorImpl.java -2]}
  {:type java.lang.UnsatisfiedLinkError
   :message Error looking up function 'godot_string_json_escape_wrapper': <PROJECT_ROOT>/build/libgodotclj_gdnative.so: undefined symbol: godot_string_json_escape_wrapper
   :at [com.sun.jna.Function <init> Function.java 252]}]
 :trace
 [[com.sun.jna.Function <init> Function.java 252]
  [com.sun.jna.NativeLibrary getFunction NativeLibrary.java 600]
  [com.sun.jna.NativeLibrary getFunction NativeLibrary.java 576]
  [com.sun.jna.NativeLibrary getFunction NativeLibrary.java 562]
  [com.sun.jna.Native register Native.java 1876]
  [tech.v3.datatype.ffi.jna.G__20113 <init> nil -1]
  [jdk.internal.reflect.NativeConstructorAccessorImpl newInstance0 NativeConstructorAccessorImpl.java -2]
  [jdk.internal.reflect.NativeConstructorAccessorImpl newInstance NativeConstructorAccessorImpl.java 62]
  [jdk.internal.reflect.DelegatingConstructorAccessorImpl newInstance DelegatingConstructorAccessorImpl.java 45]
  [java.lang.reflect.Constructor newInstance Constructor.java 490]
  [tech.v3.datatype.ffi$instantiate_class invokeStatic ffi.clj 275]
  [tech.v3.datatype.ffi$instantiate_class doInvoke ffi.clj 268]
  [clojure.lang.RestFn invoke RestFn.java 423]
  [tech.v3.datatype.ffi$instantiate_library invokeStatic ffi.clj 402]
  [tech.v3.datatype.ffi$instantiate_library invoke ffi.clj 399]
  [clojure.lang.AFn applyToHelper AFn.java 156]
  [clojure.lang.AFn applyTo AFn.java 144]
  [clojure.lang.Compiler$InvokeExpr eval Compiler.java 3706]
  [clojure.lang.Compiler$DefExpr eval Compiler.java 457]
  [clojure.lang.Compiler eval Compiler.java 7186]
  [clojure.lang.Compiler load Compiler.java 7640]
  [clojure.lang.RT loadResourceScript RT.java 381]
  [clojure.lang.RT loadResourceScript RT.java 372]
  [clojure.lang.RT load RT.java 459]
  [clojure.lang.RT load RT.java 424]
  [clojure.core$load$fn__6856 invoke core.clj 6115]
  [clojure.core$load invokeStatic core.clj 6114]
  [clojure.core$load doInvoke core.clj 6098]
  [clojure.lang.RestFn invoke RestFn.java 408]
  [clojure.core$load_one invokeStatic core.clj 5897]
  [clojure.core$load_one invoke core.clj 5892]
  [clojure.core$load_lib$fn__6796 invoke core.clj 5937]
  [clojure.core$load_lib invokeStatic core.clj 5936]
  [clojure.core$load_lib doInvoke core.clj 5917]
  [clojure.lang.RestFn applyTo RestFn.java 142]
  [clojure.core$apply invokeStatic core.clj 669]
  [clojure.core$load_libs invokeStatic core.clj 5974]
  [clojure.core$load_libs doInvoke core.clj 5958]
  [clojure.lang.RestFn applyTo RestFn.java 137]
  [clojure.core$apply invokeStatic core.clj 669]
  [clojure.core$require invokeStatic core.clj 5996]
  [clojure.core$require doInvoke core.clj 5996]
  [clojure.lang.RestFn applyTo RestFn.java 137]
  [clojure.core$apply invokeStatic core.clj 667]
  [clojure.core$serialized_require invokeStatic core.clj 6068]
  [clojure.core$requiring_resolve invokeStatic core.clj 6077]
  [godotclj.loader$_clojure_call invokeStatic loader.clj 8]
  [godotclj.loader$_clojure_call invoke loader.clj 5]
  [godotclj.loader clojure_call nil -1]]}
ERROR: Condition "!script_data" is true.
   at: _update_placeholder (modules/gdnative/nativescript/nativescript.cpp:94)
ERROR: Condition "!script_data" is true.
   at: _update_placeholder (modules/gdnative/nativescript/nativescript.cpp:94)
ERROR: Condition "!script_data" is true.
   at: _update_placeholder (modules/gdnative/nativescript/nativescript.cpp:94)
ERROR: In Object of type 'Area2D': Attempt to connect nonexistent signal 'hit' to method 'Node.game_over'.
   at: connect (core/object.cpp:1462)
ERROR: In Object of type 'CanvasLayer': Attempt to connect nonexistent signal 'start_game' to method 'Node.new_game'.
   at: connect (core/object.cpp:1462)
```
## Things that were not found

After trying to run the editor again, I've got different results for the functions that were not found. Other than that, stack trace remained the same.

1.  `godot_string_json_escape_wrapper`
2.  `godot_transform_xform_vector3_wrapper`
3.  `godot_global_get_singleton_wrapper`
4.  `godot_vector2_operator_divide_vector_wrapper`
5.  `godot_pool_string_array_write_access_ptr_wrapper`
6.  `godot_array_get_wrapper`
7.  `godot_pool_string_array_write_access_ptr_wrapper`
8.  `godot_variant_new_node_path_wrapper`
9.  `godot_pool_string_array_write_access_ptr_wrapper`
10. `godot_pool_byte_array_new_with_array_wrapper`
11. `godot_node_path_get_subname_count_wrapper`
12. `godot_pool_vector3_array_set_wrapper`

**Comment by tristanstraub** [comment]
Thanks for the issue. Some very good detail here.

The meander warning shouldn't affect anything. Meander is only used during C code generation. I used it to satisfy my own curiousity, but it isn't being used efficiently. The warning has been there all the time, but could be addressed eventually.

The times are consistent with what I have seen with a working version. They can be vastly improved by some targeted AOT compilation.

I have seen that godot will change the game files if methods/signals cannot be found because gdnative failed to load.

The missing symbols are strange, and I'll have to reproduce it to see.

**Comment by tristanstraub** [comment]
Seems related to https://stackoverflow.com/questions/14329967/missing-a-library-in-ldd-after-using-gcc-l

Running "ldd bin/libgodotclj_gdnative.so" does not show libwrapper.so as a dependency.

Can you try adding "-Wl,--no-as-needed" to the "gcc" command in godotclj/Makefile under target "$(BUILD)/libgodotclj_gdnative.so: $(BUILD)/jvm.o [...]". It should now look like the following:
```sh
	gcc $(CFLAGS) -Wl,--no-as-needed -Wl,-rpath='$$ORIGIN' -shared -o $@ -I$(BUILD) -I$(GODOT_HEADERS) -Isrc/c --std=c11 -fPIC -rdynamic -L$(BUILD) $(BUILD)/gdnative.o $(BUILD)/callback.o $(BUILD)/godot_bindings.o $(BUILD)/jvm.o -I $(JAVA_HOME)/include -I $(JAVA_HOME)/include/linux -ljava -ljvm -L $(JAVA_HOME)/lib -L $(JAVA_HOME)/lib/server -L /usr/lib64 -lwrapper -L$(BUILD)
```
Run "make clean all", and then start the editor again.

**Comment by tristanstraub** [comment]
To help speed things up, try "make aot" from thecreeps project before running the editor, or the game.

I haven't resolved the libasound error.

**Comment by 3starblaze** [comment]
> Can you try adding "-Wl,--no-as-needed" to the "gcc" command in godotclj/Makefile under target "$(BUILD)/libgodotclj_gdnative.so: $(BUILD)/jvm.o [...]". It should now look like the following:

Yes, this did the trick and now it works. I tried changing the code a bit and connecting to nrepl and that part went without problem. The same libasound error is still there but the game and the sound works fine.

The only problem that is not described in `readme` is that there's this error where godot breaks configs and tscn files by using comma instead of dot for decimal delimiter. For instance, I changed `MobTimer` wait time to 0.1 in the editor and this happened:
```diff
modified   src/godot/main.tscn
@@ -19,7 +19,7 @@ Mob = ExtResource( 3 )
 [node name="ColorRect" type="ColorRect" parent="."]
 anchor_right = 1.0
 anchor_bottom = 1.0
-color = Color( 0.356863, 0.0784314, 0.486275, 1 )
+color = Color( 0,356863, 0,0784314, 0,486275, 1 )
 __meta__ = {
 "_edit_use_anchors_": false
 }
@@ -27,7 +27,7 @@ __meta__ = {
 [node name="Player" parent="." instance=ExtResource( 2 )]
 
 [node name="MobTimer" type="Timer" parent="."]
-wait_time = 0.1
+wait_time = 0,1.0
 
 [node name="ScoreTimer" type="Timer" parent="."]
```
That probably deserves another issue but I figured it's worth mentioning here.

**Comment by 3starblaze** [comment]
I'll make a PR to godotclj repo with this fix. Shall I also make a PR to this repo by adding my OS to the tested OS list?

**Comment by tristanstraub** [comment]
Great that is now working!

The "comma" issue is probably a godot issue, rather than godotclj. It feels like a localization issue. Perhaps, the region your computer is set to is overriding this formatting?

.... I checked the open issues in godot and found this https://github.com/godotengine/godot/issues/48148#issuecomment-826070282 which sounds like a good lead. And this in godot-kotlin https://github.com/utopia-rise/godot-kotlin-jvm/issues/166

**Comment by tristanstraub** [comment]
Looks like the fix in godot-kotlin overrides the local here https://github.com/utopia-rise/godot-kotlin-jvm/pull/173/files. Might be worth a try, though I don't quite understand how "global" is set.

**Comment by tristanstraub** [comment]
Yeah, a PR for the OS in the README would be great.

**Comment by tristanstraub** [comment]
I can reproduce the comma issue locally by setting my locale to Russian Federation. I see the following environment variables before I run godot:
```
LC_NUMERIC=ce_RU.UTF-8
LC_TIME=ce_RU.UTF-8
LC_MONETARY=ce_RU.UTF-8
LC_PAPER=ce_RU.UTF-8
LC_MEASUREMENT=ce_RU.UTF-8
```

**Comment by tristanstraub** [comment]
I've created a fix for the comma/locale issue in godotclj. I'm just chasing another defect in thecreeps before merging the fix.

**Comment by tristanstraub** [comment]
Try https://github.com/tristanstraub/thecreeps-godotclj/pull/3 which fixes the locale issue. It does need a submodule update.

**Comment by 3starblaze** [comment]
> Try #3 which fixes the locale issue. It does need a submodule update.

Yes, this resolved my previously-mentioned issue. It's a rather strange bug because that doesn't happen when I make games with gdscript.

**Comment by tristanstraub** [comment]
Yeah, I think godot must set the locale used by libc to something universal, and then the JVM sets it back to the system locale when it starts within the godot process.
